const express = require('express')
const router = express.Router()
const authController = require('../controllers/driverController')
const controller = require('../controllers/driverController')
const verify = require('../middleware/verifyJWT')